# Generated by Django 4.2.25 on 2025-10-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tblProperty',
            fields=[
                ('PropertyID', models.AutoField(primary_key=True, serialize=False)),
                ('PropertyHouseNumber', models.IntegerField()),
                ('PropertyPostcode', models.CharField(max_length=6)),
                ('Bedrooms', models.IntegerField()),
            ],
        ),
    ]
