# Generated by Django 5.2.7 on 2025-10-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('quote_text', models.TextField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('additional_details', models.TextField(max_length=100)),
            ],
        ),
    ]
